require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Admin::IdeasController do

  # This should return the minimal set of attributes required to create a valid
  # Admin::Idea. As you add validations to Admin::Idea, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Admin::IdeasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all admin_ideas as @admin_ideas" do
      idea = Admin::Idea.create! valid_attributes
      get :index, {}, valid_session
      assigns(:admin_ideas).should eq([idea])
    end
  end

  describe "GET show" do
    it "assigns the requested admin_idea as @admin_idea" do
      idea = Admin::Idea.create! valid_attributes
      get :show, {:id => idea.to_param}, valid_session
      assigns(:admin_idea).should eq(idea)
    end
  end

  describe "GET new" do
    it "assigns a new admin_idea as @admin_idea" do
      get :new, {}, valid_session
      assigns(:admin_idea).should be_a_new(Admin::Idea)
    end
  end

  describe "GET edit" do
    it "assigns the requested admin_idea as @admin_idea" do
      idea = Admin::Idea.create! valid_attributes
      get :edit, {:id => idea.to_param}, valid_session
      assigns(:admin_idea).should eq(idea)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Admin::Idea" do
        expect {
          post :create, {:admin_idea => valid_attributes}, valid_session
        }.to change(Admin::Idea, :count).by(1)
      end

      it "assigns a newly created admin_idea as @admin_idea" do
        post :create, {:admin_idea => valid_attributes}, valid_session
        assigns(:admin_idea).should be_a(Admin::Idea)
        assigns(:admin_idea).should be_persisted
      end

      it "redirects to the created admin_idea" do
        post :create, {:admin_idea => valid_attributes}, valid_session
        response.should redirect_to(Admin::Idea.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved admin_idea as @admin_idea" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Idea.any_instance.stub(:save).and_return(false)
        post :create, {:admin_idea => {  }}, valid_session
        assigns(:admin_idea).should be_a_new(Admin::Idea)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Idea.any_instance.stub(:save).and_return(false)
        post :create, {:admin_idea => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested admin_idea" do
        idea = Admin::Idea.create! valid_attributes
        # Assuming there are no other admin_ideas in the database, this
        # specifies that the Admin::Idea created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Admin::Idea.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => idea.to_param, :admin_idea => { "these" => "params" }}, valid_session
      end

      it "assigns the requested admin_idea as @admin_idea" do
        idea = Admin::Idea.create! valid_attributes
        put :update, {:id => idea.to_param, :admin_idea => valid_attributes}, valid_session
        assigns(:admin_idea).should eq(idea)
      end

      it "redirects to the admin_idea" do
        idea = Admin::Idea.create! valid_attributes
        put :update, {:id => idea.to_param, :admin_idea => valid_attributes}, valid_session
        response.should redirect_to(idea)
      end
    end

    describe "with invalid params" do
      it "assigns the admin_idea as @admin_idea" do
        idea = Admin::Idea.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Idea.any_instance.stub(:save).and_return(false)
        put :update, {:id => idea.to_param, :admin_idea => {  }}, valid_session
        assigns(:admin_idea).should eq(idea)
      end

      it "re-renders the 'edit' template" do
        idea = Admin::Idea.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Idea.any_instance.stub(:save).and_return(false)
        put :update, {:id => idea.to_param, :admin_idea => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested admin_idea" do
      idea = Admin::Idea.create! valid_attributes
      expect {
        delete :destroy, {:id => idea.to_param}, valid_session
      }.to change(Admin::Idea, :count).by(-1)
    end

    it "redirects to the admin_ideas list" do
      idea = Admin::Idea.create! valid_attributes
      delete :destroy, {:id => idea.to_param}, valid_session
      response.should redirect_to(admin_ideas_url)
    end
  end

end
